# Generated by Django 5.0.4 on 2024-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=180)),
                ("sehir", models.CharField(max_length=50)),
                ("ulke", models.CharField(max_length=80)),
                ("kod", models.CharField(max_length=8)),
            ],
        ),
    ]
