# Generated by Django 5.0.4 on 2024-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ucus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ucak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=150)),
                ("marka", models.CharField(max_length=120)),
                ("model", models.CharField(max_length=120)),
                ("yil", models.IntegerField()),
                ("kapasite", models.IntegerField()),
                ("hiz", models.FloatField()),
                ("boy", models.FloatField()),
                ("ulke", models.CharField(max_length=120)),
                ("detay", models.TextField()),
                ("resim", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
