# Generated by Django 5.0.4 on 2024-04-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ucus", "0002_ucak"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ucak",
            options={"verbose_name": "Jet", "verbose_name_plural": "Jetler"},
        ),
        migrations.CreateModel(
            name="Rota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=120)),
                (
                    "kalkis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Kalkış",
                        to="ucus.airport",
                    ),
                ),
                (
                    "ucak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ucus.ucak"
                    ),
                ),
                (
                    "varis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Varış",
                        to="ucus.airport",
                    ),
                ),
            ],
        ),
    ]
