# Generated by Django 5.0.4 on 2024-04-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ucus", "0003_alter_ucak_options_rota"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rota",
            options={
                "verbose_name": "Uçus Rotası",
                "verbose_name_plural": "Uçuş Rotaları",
            },
        ),
        migrations.CreateModel(
            name="RotaPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField()),
                ("ucret", models.FloatField()),
                ("vale", models.BooleanField()),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "rota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Rota",
                        to="ucus.rota",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planlanmış Uçuş",
                "verbose_name_plural": "Planlanmış Uçuşlar",
            },
        ),
    ]
