# Generated by Django 5.0.4 on 2024-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ucus", "0005_rezervasyon"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="aciklama",
            field=models.TextField(blank=True, null=True),
        ),
    ]
